import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'ar' | 'en';
  setLanguage: (lang: 'ar' | 'en') => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  ar: {
    // Navigation
    home: 'الرئيسية',
    about: 'عن المدرسة',
    programs: 'البرامج التعليمية',
    activitiesNav: 'الأنشطة',
    gallery: 'معرض الصور',
    contact: 'اتصل بنا',
    enrollment: 'التسجيل',
    schoolName: 'مدارس المختار النموذجية',
    schoolNameAr: 'مدارس المختار النموذجية',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    dashboard: 'لوحة التحكم',
    logout: 'تسجيل الخروج',
    language: 'English',
    arabicLanguage: 'العربية',
    englishLanguage: 'English',
    mapLabel: 'مدارس المختار النموذجية',
    
    // About Page Education
    phD: 'دكتور أسنان',
     medCurriculum: 'شهادة جامعية في الهندسة المدنية',
     maPsychology: 'دكتور اختصاص هضم',
     educationBackground: 'الخلفية التعليمية',
     teachingExperience: 'الخبرة التدريسية',
     certifications: 'الشهادات',
     
     // Gallery Page
    galleryTitle: 'معرض الصور',
    galleryDescription: 'استكشف حياة مدرستنا النابضة بالحياة من خلال الصور',
    gallerySubtitle: 'استكشف مرافق مدرستنا وأنشطة الطلاب',
    photoCategories: 'فئات الصور',
    all: 'الكل',
    classrooms: 'الصفوف',
    facilities: 'المرافق',
    sportsActivity: 'الرياضة',
    events: 'الفعاليات',
    activities: 'الأنشطة',
    students: 'الطلاب',
    noImagesFound: 'لا توجد صور',
    tryDifferentCategory: 'حاول اختيار فئة مختلفة',
    galleryImage: 'صورة المعرض',
    photos: 'صور',
    
    // Gallery Image Titles
    modernClassroom: 'الصف الحديث',
    scienceLaboratory: 'مختبر العلوم',
    sportsDayActivity: 'اليوم الرياضي',
    graduation: 'التخرج 2024',
    artWorkshop: 'ورشة الفنون',
    schoolLibrary: 'مكتبة المدرسة',
    groupStudy: 'الدراسة الجماعية',
    chemistryLab: 'مختبر الكيمياء',
    scienceFairActivity: 'مخبر العلوم',
    computerLab: 'مختبر الحاسوب',
    techIntegration: 'التعلم التقني',
    musicConcert: 'الحفل الموسيقي',
    
    // Hero Section
    heroTitle: 'مدارس المختار النموذجية',
    heroSubtitle: 'نبني جيلاً، نصنع مجداً',
    heroDescription: 'نقدم تعليمًا عالي الجودة يجمع بين التميز الأكاديمي والقيم الإسلامية لتخريج أجيال قادرة على مواجهة تحديات المستقبل',
    heroLearnMore: 'تعرف أكثر',
    enrollNow: 'سجل الآن',
    graduates: 'خريجين',
    schoolHistory: 'تاريخ المدرسة',
    leadershipTeam: 'فريق الإدارة',
    
    // School History
    historyParagraph1: 'تأسست مدارس المختار النموذجية في عام 2011 كرؤية لتوفير فرص تعليمية استثنائية للطلاب في دمشق. بدأنا بـ 50 طالبًا و10 معلمين فقط، ونمونا لنصبح واحدة من أكثر المؤسسات التعليمية الخاصة احترامًا في سوريا.',
    historyParagraph2: 'تميزت رحلتنا بالتحسين المستمر والابتكار في منهجيات التدريس وتطوير البنية التحتية وإنجازات الطلاب. لقد حافظنا باستمرار على معايير أكاديمية عالية مع التكيف مع الاحتياجات التعليمية الحديثة.',
    historyParagraph3: 'اليوم، نخدم بفخر أكثر من 1700 طالب عبر جميع المستويات التعليمية، من رياض الأطفال إلى المدرسة الثانوية، مع فريق متفاني من المعلمين المؤهلين وأعضاء هيئة التدريس الملتزمين بالتميز في التعليم.',
    
    // About Section
    aboutTitle: 'من نحن',
    aboutDescription: 'مدارس المختار النموذجية مؤسسة تعليمية رائدة تأسست عام 2011 بهدف تقديم تعليم متميز يجمع بين التميز الأكاديمي والقيم الإسلامية',
    mission: 'رسالتنا',
    missionText: 'تقديم تعليم متميز يجمع بين التميز الأكاديمي والقيم الإسلامية لتخريج أجيال قادرة على مواجهة تحديات المستقبل',
    vision: 'رؤيتنا',
    visionText: 'أن نكون مدرسة رائدة في المنطقة تقدم تعليماً متميزاً يجمع بين الأصالة والمعاصرة لبناء جيل واعٍ قادر على الإبداع والمنافسة',
    values: 'قيمنا',
    valuesText: 'التميز، الابتكار، القيم الإسلامية، احترام الفرد، المسؤولية الاجتماعية',
    
    // Programs
  programsTitle: 'برامجنا التعليمية',
  programsSubtitle: 'تعليم شامل من رياض الأطفال إلى المرحلة الثانوية',
  educationalStages: 'مراحل التعليم',
  educationalStagesDesc: 'نقدم رحلة تعليمية شاملة مصممة لرعاية الطلاب في كل مرحلة من مراحل تطورهم، من مرحلة الطفولة المبكرة وحتى التخرج من المدرسة الثانوية',
  educationalStagesDescription: 'نقدم برامج تعليمية متكاملة تلبي احتياجات الطلاب في جميع المراحل الدراسية، مع التركيز على التطوير الشامل للمهارات الأكاديمية والشخصية',
  coreSubjects: 'المواد الأساسية',
  keyFeatures: 'الميزات الرئيسية',
  
  // Kindergarten Features
  kindergartenFeature1: 'بيئة تعليمية آمنة ومحفزة',
  kindergartenFeature2: 'أنشطة تفاعلية تنمي المهارات الأساسية',
  kindergartenFeature3: 'تطوير المهارات الاجتماعية والعاطفية',
  kindergartenFeature4: 'تعزيز حب التعلم والاستكشاف',
  kindergartenFeature5: 'تنمية المهارات اللغوية المبكرة',
  kindergartenFeature6: 'أنشطة حركية لتطوير المهارات الحركية',
  kindergartenProgram: 'برنامج رياض الأطفال',
  earlyChildhood: 'مرحلة الطفولة المبكرة',
  kindergartenAgeRange: '3-5 سنوات',
  kindergartenFeatures: 'مميزات البرنامج',
  kindergartenApproach: 'منهجنا التعليمي',
  kindergartenApproachText: 'نعتمد منهجاً تعليمياً متكاملاً يجمع بين اللعب والتعلم، ويركز على تنمية مهارات الطفل الاجتماعية والعاطفية والمعرفية والحركية.',
  kindergartenSubjects: 'المواد الدراسية',

   // Elementary Features
  elementaryFeature1: 'منهج متكامل يركز على المهارات الأساسية',
  elementaryFeature2: 'تطوير مهارات القراءة والكتابة والحساب',
  elementaryFeature3: 'أنشطة إبداعية وفنية متنوعة',
  elementaryFeature4: 'بناء أساس متين للمراحل التعليمية اللاحقة',
  elementaryFeature5: 'تعزيز الثقة بالنفس والاستقلالية',
  elementaryFeature6: 'تنمية مهارات التواصل والعمل الجماعي',
  elementaryProgram: 'برنامج المرحلة الابتدائية',
   primaryEducation: 'التعليم الأساسي',

   // Middle School Features
  middleFeature1: 'تعزيز مهارات التفكير النقدي وحل المشكلات',
  middleFeature2: 'تطوير المهارات البحثية والتحليلية',
  middleFeature3: 'اكتشاف المواهب والميول الشخصية',
  middleFeature4: 'إعداد الطلاب للمرحلة الثانوية',
  middleFeature5: 'تنمية مهارات القيادة والمسؤولية',
  middleFeature6: 'تعزيز الهوية الشخصية والثقة بالنفس',
  middleProgram: 'برنامج المرحلة المتوسطة',
   intermediateEducation: 'التعليم المتوسط',

   // High School Features
  highFeature1: 'منهج أكاديمي متقدم يؤهل للجامعة',
  highFeature2: 'استغلال الذكاء الاسطناعي لعمل فعال  و نتائج أسرع',
  highFeature3: 'فرص قيادية وأنشطة تطوعية',
   highFeature4: 'إعداد شامل للحياة الجامعية والمهنية',
   highFeature5: 'تطوير مهارات التفكير النقدي والإبداعي',
   highFeature6: 'فرص للتدريب العملي والتجارب المهنية',
   highProgram: 'برنامج المرحلة الثانوية',
   secondaryEducation: 'التعليم الثانوي',
   learnMore: 'اعرف المزيد',
  teachingApproach: 'أسلوبنا التعليمي',
  ourTeachingApproach: 'أسلوبنا التعليمي',
  flexibleSchedule: 'جدول مرن',
  flexibleScheduleDesc: 'جدول يومي متوازن مع المواد الأكاديمية والأنشطة وفترات الراحة',
  smallClassSizes: 'فصول صغيرة',
  smallClassSizesDesc: 'بحد أقصى 30 طالبًا في الفصل لضمان الاهتمام والدعم الفردي',
  excellenceFocus: 'التركيز على التميز',
  excellenceFocusDesc: 'الالتزام بالتميز الأكاديمي وتنمية الشخصية',
  
  // Program Descriptions
  kindergartenDescription: 'برنامج تعليمي مبتكر للأطفال من 3-5 سنوات يركز على التنمية الشاملة',
  elementaryDescription: 'تعليم أساسي متميز من الصف الأول إلى السادس مع التركيز على المهارات الأساسية',
  middleDescription: 'تعليم متوسط شامل من الصف السابع إلى التاسع يعد الطلاب للمرحلة الثانوية',
  highDescription: 'تعليم ثانوي متقدم يعد الطلاب للجامعة والحياة المهنية',
  
  // Program Features
  playBasedLearning: 'نهج التعلم القائم على اللعب',
  socialEmotionalDevelopment: 'التنمية الاجتماعية والعاطفية',
  socialEmotionalDev: 'التنمية الاجتماعية والعاطفية',
  basicLiteracy: 'مهارات القراءة والكتابة والحساب الأساسية',
  creativeArts: 'الفنون والحرف الإبداعية',
  physicalDevelopment: 'أنشطة التنمية البدنية',
  physicalDev: 'أنشطة التنمية البدنية',
  characterBuilding: 'بناء الشخصية',
  comprehensiveCurriculum: 'منهج شامل',
  individualAttention: 'اهتمام فردي',
  technologyIntegration: 'دمج التكنولوجيا',
  projectBasedLearning: 'التعلم القائم على المشاريع',
  extracurricularActivities: 'أنشطة خارج المنهج',
  extracurricular: 'أنشطة لا منهجية',
  parentTeacherCollaboration: 'تعاون بين الآباء والمعلمين',
  parentTeacherCollab: 'تعاون بين الأهل والمعلمين',
  advancedCurriculum: 'منهج متقدم',
  criticalThinking: 'تنمية التفكير النقدي',
  leadershipOpportunities: 'فرص القيادة',
  specializedLaboratories: 'مختبرات متخصصة',
  specializedLabs: 'مختبرات متخصصة',
  careerExploration: 'استكشاف المهن',
  peerCollaboration: 'التعاون بين الأقران',
  universityPreparation: 'الإعداد للجامعة',
  universityPrep: 'التحضير للجامعة',
  advancedPlacement: 'دورات متقدمة',
  researchProjects: 'مشاريع بحثية',
  collegeAdvising: 'الإرشاد الجامعي',
  internshipOpportunities: 'فرص التدريب',
  leadershipDevelopment: 'تنمية القيادة',
  leadershipDev: 'تنمية القيادة',
  
  // Subjects
  english: 'اللغة الإنجليزية',
  arabic: 'اللغة العربية',
  math: 'الرياضيات',
  arts: 'الفنون',
  music: 'إكتشاف المهارات',
  physicalEducation: 'التربية البدنية',
  mathematics: 'الرياضيات',
  science: 'العلوم',
  socialStudies: 'الدراسات الاجتماعية',
  advancedEnglish: 'اللغة الإنجليزية المتقدمة',
  arabicLiterature: 'الأدب العربي',
  advancedMathematics: 'الرياضيات المتقدمة',
  physicsChemistry: 'الفيزياء والكيمياء',
  biology: 'علم الأحياء',
  computerScience: 'الذكاء الاسطناعي',
  physics: 'الفيزياء',
  chemistry: 'الكيمياء',
  kindergarten: 'رياض الأطفال',
  kindergartenDesc: 'برنامج تعليمي مبتكر للأطفال من 3-5 سنوات يركز على التنمية الشاملة',
  elementary: 'المرحلة الابتدائية',
  elementaryDesc: 'تعليم أساسي متميز من الصف الأول إلى السادس مع التركيز على المهارات الأساسية',
  middle: 'المرحلة المتوسطة',
  middleDesc: 'تعليم متوسط شامل من الصف السابع إلى التاسع يعد الطلاب للمرحلة الثانوية',
  high: 'المرحلة الثانوية',
  highDesc: 'تعليم ثانوي متقدم يعد الطلاب للجامعة والحياة المهنية',
    
    // Activities
    activitiesTitle: 'الأنشطة والأخبار',
    activitiesSubtitle: 'اكتشف مجتمع مدرستنا النابض بالحياة من خلال الفعاليات والإنجازات',
    activityCategories: 'فئات الأنشطة',
    upcomingActivities: 'الأنشطة القادمة والأحداث',
    latestNews: 'آخر الأخبار',
    recentAchievements: 'إنجازات مميزة',
    scienceFair: 'مخبر علوم الأحياء',
    scienceFairDate: '13 أبريل 2025',
    scienceFairDesc: 'تشريح أرنب للتعرف على عجائب اجسام الكائنات الحية',
    sportsDay: 'دوري كرة القدم',
    sportsDayDate: '11 نوفمبر 2024',
    sportsDayDesc: 'دوري في رياضة كرة القدم على مستوى المدارس',
    culturalFestival: 'دار الفكر',
    culturalFestivalDate: '30 أكتوبر 2024',
    culturalFestDesc: 'إيداء وصول لتنويعة من الكتب مثيرة الاهتمام',
    modelUN: 'عيد مدارس المختار',
    modelUNDate: '14 أبريل 2025',
    munDesc: 'تجمع طلاب المختار في مختلف الفعاليات و النشاطات المسلية',
    musicArtsShowcase: 'معرض مرسومات الطلاب',
    musicArtsDate: '24 ماي 2025',
    artsShowcaseDesc: 'عروض طلابية لمختلف انواع الرسمات منها الخيالية و منها الحقيقية',
    mathOlympiad: 'مسابقة الشطرنج',
    mathOlympiadDate: '16 ديسمبر 2024',
    mathOlympiadDesc: 'مسابقة الشطرنج بين طلاب مدارس مختلفة بنظام النقاط الأوروبي',
    participants150: '30 طالب',
    participantsAll: '11 طالب',
    participants200: 'جميع الطلاب',
    participantsHighSchool: 'جميع الطلاب',
    participants80: '5 مؤدي',
    participants30: '10 طالب',
    p: 'مدارس المختار النموذجية',
    newLabTitle: 'رعاية المهارات استخدام الحاسوب بتعليم الـICDL',
    newLabDate: '20 سيبتمبر 2024',
    newLabSummary: 'في صفي 10 و 11 لإعداد طلاب متمرسة من الحاسوب',
    debateWinTitle: 'طلابنا يشاركون في المناظرة القطرية الإقليمية',
    debateWinDate: '15 فبراير 2024',
    debateWinSummary: 'فريق المناظرة يحقق فوز في بطولة سوريا المحلية',
    newLibraryTitle: 'إعطاء منح مدرسية لـ100+ طلاب',
    newLibraryDate: '16 سيبتمبر 2024',
    newLibrarySummary: 'منح الطلاب المتفوقين حسومات و منح للتسجيل',
    
    // Activity Descriptions
    "Rabbit dissection experiment to discover the wonders inside living organisms": "تشريح أرنب للتعرف على عجائب اجسام الكائنات الحية",
    "Inter-class competitions in various sports activities": "دوري في رياضة كرة القدم على مستوى المدارس",
    "Celebration of Syrian culture through music, dance, and art": "احتفال بالثقافة السورية من خلال الموسيقى والرقص والفن",
    "Students debate global issues and develop diplomatic skills": "يناقش الطلاب القضايا العالمية ويطورون المهارات الدبلوماسية",
    "Student performances in music, theater, and visual arts": "عروض الطلاب في الموسيقى والمسرح والفنون البصرية",
    "Regional mathematics competition with challenging problems": "مسابقة رياضيات إقليمية مع مسائل تحدي",
    
    // Participant Counts
    "150 students": "150 طالب",
    "11 Students": "11 طالب",
    "200+ attendees": "جميع الطلاب",
    "High school students": "طلاب المرحلة الثانوية",
    "80 performers": "80 مؤدي",
    "30 students": "30 طالب",
    
    // Activity Descriptions
    activityDescription1: 'مسابقة الروبوتات السنوية حيث يتنافس الطلاب في تصميم وبرمجة الروبوتات',
    activityDescription2: 'معرض الفنون السنوي لعرض إبداعات الطلاب الفنية',
    activityDescription3: 'رحلة علمية إلى متحف العلوم لاستكشاف العلوم التطبيقية',
    activityDescription4: 'مخيم صيفي تعليمي يجمع بين المرح والتعلم',
    activityDate: 'التاريخ: 15 مايو 2024',
    studentAmount: 'عدد الطلاب: 30 طالب',
    newsDescription1: 'فاز فريق المدرسة بالمركز الأول في مسابقة العلوم الوطنية',
    newsDescription2: 'افتتاح مختبر الحاسوب الجديد المجهز بأحدث التقنيات',
    newsDescription3: 'تكريم طلاب المدرسة المتفوقين في الاختبارات النهائية',
    "State-of-the-art laboratory equipment installed for enhanced learning experience": "تم تركيب معدات مختبرية متطورة لتعزيز تجربة التعلم",
    "Our debate team secured first place in the Damascus Regional Championship": "حصل فريق المناظرة لدينا على المركز الأول في بطولة دمشق الإقليمية",
    "Expanded library facilities with digital resources and quiet study areas": "توسيع مرافق المكتبة مع موارد رقمية ومناطق دراسة هادئة",
    fieldTrip: 'رحلة ميدانية',
     roboticsCompetition: 'مسابقة الروبوتات',
     summerCamp: 'المخيم الصيفي',
     artExhibition: 'معرض الفنون',
     bestSchoolAward: 'جائزة أفضل مدرسة',
    graduationRate: '100% نجاح',
    scholarshipsAwarded: '15 منحة جامعية',
    sports: 'الرياضة',
    sportsDesc: 'برامج رياضية متنوعة لتنمية المهارات البدنية وروح الفريق',
    artsActivity: 'الفنون',
    artsDesc: 'أنشطة فنية إبداعية لتنمية المواهب الفنية والإبداعية',
    scienceActivity: 'العلوم',
    scienceDesc: 'أنشطة علمية عملية لتحفيز الفضول العلمي والاكتشاف',
    community: 'خدمة المجتمع',
    communityDesc: 'برامج خدمة مجتمع لتنمية المسؤولية الاجتماعية',
    
    // About Page
    achievements: 'إنجازاتنا',
    yearsOfExcellence: 'سنوات من التميز',
    studentsCategory: 'طلاب',
    teachers: 'معلمون',
    successRate: 'نسبة النجاح',
    
    // Contact
    contactTitle: 'اتصل بنا',
    contactSubtitle: 'تواصل مع مدارس المختار النموذجية',
    contactInformation: 'معلومات الاتصال',
    contactInfo: 'معلومات التواصل',
    addressLabel: 'العنوان',
    addressValue: 'دمشق، سوريا',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    emailValue: 'info@al-mukhtar.edu.sy',
    workingHours: 'ساعات العمل',
    workingHoursValue: 'الأحد - الخميس: 8:00 ص - 3:00 م',
    officeHours: 'ساعات المكتب',
    administrationOffice: 'مكتب الإدارة',
    generalInformation: 'المعلومات العامة',
    sendMessage: 'أرسل رسالة',
    yourFullName: 'الاسم الكامل',
    yourEmail: 'البريد الإلكتروني',
    yourPhone: 'رقم الهاتف',
    messageSubject: 'موضوع الرسالة',
    yourMessage: 'رسالتك',
    sendMessageButton: 'إرسال الرسالة',
    coordinates: 'الإحداثيات',
    followUs: 'تابعونا',
    yourName: 'الاسم',
    message: 'الرسالة',
    
    // Enrollment
    enrollmentTitle: 'التسجيل',
    enrollmentProcess: 'خطوات التسجيل',
    step1: 'ملء النموذج',
    step1Desc: 'املأ نموذج التسجيل بالمعلومات المطلوبة',
    step2: 'المراجعة',
    step2Desc: 'سنراجع طلبك ونتواصل معك',
    step3: 'المقابلة',
    step3Desc: 'حضور مقابلة مع الطالب وولي الأمر',
    step4: 'التسجيل النهائي',
    step4Desc: 'إكمال التسجيل ودفع الرسوم',
    enrollmentHeroDesc: 'انضم إلى مجتمعنا التعليمي وابدأ رحلتك نحو التميز الأكاديمي',
    enrollmentForm: 'نموذج التسجيل',
    studentInfo: 'معلومات الطالب',
    studentName: 'اسم الطالب',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'الجنس',
    selectGender: 'اختر الجنس',
    male: 'ذكر',
    female: 'أنثى',
    gradeLevel: 'الصف الدراسي',
    selectGrade: 'اختر الصف',
    kg1: 'روضة أولى',
    kg2: 'روضة ثانية',
    grade1: 'الصف الأول',
    grade2: 'الصف الثاني',
    grade3: 'الصف الثالث',
    grade4: 'الصف الرابع',
    grade5: 'الصف الخامس',
    grade6: 'الصف السادس',
    grade7: 'الصف السابع',
    grade8: 'الصف الثامن',
    grade9: 'الصف التاسع',
    grade10: 'الصف العاشر',
    grade11: 'الصف الحادي عشر',
    grade12: 'الصف الثاني عشر',
    previousSchool: 'المدرسة السابقة',
    parentInfo: 'معلومات ولي الأمر',
    parentName: 'اسم ولي الأمر',
    phoneNumber: 'رقم الهاتف',
    emailAddress: 'البريد الإلكتروني',
    address: 'العنوان',
    additionalInfo: 'معلومات إضافية',
    additionalNotes: 'ملاحظات إضافية',
    agreeToTerms: 'أوافق على شروط وأحكام التسجيل وسياسة الخصوصية',
    submitEnrollment: 'إرسال طلب التسجيل',
    requiredFields: 'الحقول المميزة بعلامة * مطلوبة',
    tuitionFees: 'الرسوم الدراسية',
    tuitionFeesDesc: 'تختلف الرسوم الدراسية حسب المرحلة التعليمية. يرجى الاطلاع على الجدول أدناه للحصول على معلومات مفصلة.',
    annualFees: 'الرسوم السنوية',
    registrationFee: 'رسوم التسجيل',
    paymentOptions: 'خيارات الدفع',
    paymentOptionsValue: 'سنوي، نصف سنوي، ربع سنوي',
    elementarySchool: 'المرحلة الابتدائية',
    middleSchool: 'المرحلة المتوسطة',
    highSchool: 'المرحلة الثانوية',
    paymentOptionsList: 'دفعة واحدة (خصم 5%)، دفعتين (بداية كل فصل دراسي)، أربع دفعات (كل شهرين)',
    paymentOptionsList1: 'دفعة واحدة (خصم 5%)',
    paymentOptionsList2: 'دفعتين (بداية كل فصل دراسي)',
    paymentOptionsList3: 'أربع دفعات (كل شهرين)',
    feesIncludeNote: 'الرسوم تشمل الكتب الدراسية والزي المدرسي والأنشطة الأساسية.',
    additionalFeesNote: 'قد تطبق رسوم إضافية على بعض الأنشطة والرحلات الخاصة.',
    faq: 'الأسئلة الشائعة',
    faqTitle: 'الأسئلة الشائعة',
    faqDocumentsQuestion: 'ما هي المستندات المطلوبة للتسجيل؟',
    faqDocuments: 'ما هي المستندات المطلوبة للتسجيل؟',
    faqDocumentsAnswer: 'شهادة ميلاد الطالب، صورة من جواز السفر، شهادات دراسية سابقة، صور شخصية حديثة، تقارير طبية (إن وجدت).',
    faqAdmissionTestQuestion: 'هل هناك اختبار قبول للطلاب الجدد؟',
    faqAdmissionTest: 'هل هناك اختبار قبول للطلاب الجدد؟',
    faqAdmissionTestAnswer: 'نعم، يخضع الطلاب لاختبار تحديد مستوى في اللغة الإنجليزية والرياضيات للصفوف من الأول إلى الثاني عشر.',
    faqTransportationQuestion: 'هل توفر المدرسة خدمة النقل؟',
    faqTransportation: 'هل توفر المدرسة خدمة النقل؟',
    faqTransportationAnswer: 'نعم، توفر المدرسة خدمة النقل بحافلات مكيفة ومجهزة بأنظمة تتبع وكاميرات مراقبة لضمان سلامة الطلاب.',
    faqSiblingDiscountQuestion: 'هل هناك خصومات للأشقاء؟',
    faqSiblingDiscount: 'هل هناك خصومات للأشقاء؟',
    faqSiblingDiscountAnswer: 'نعم، تقدم المدرسة خصماً بنسبة 10% للطفل الثاني و15% للطفل الثالث وما فوق.',
    successTitle: 'تم تقديم الطلب',
    successMessage: 'تم تقديم طلب التسجيل بنجاح. سنتواصل معك قريبًا.',
    quickLinks: 'روابط سريعة',
    followUsText: 'تابعنا',
    schoolDescription: 'مؤسسة تعليمية خاصة توفر تعليماً عالي الجودة من مرحلة الروضة إلى المرحلة الثانوية في دمشق، سوريا.',
    schoolAddress: 'دمشق، سوريا',
    schoolPhone: '+963 992 514 002',
    schoolEmail: 'info@al-mukhtar.edu.sy',
    rights: '© 2025 مدارس المختار النموذجية. جميع الحقوق محفوظة.',
    
    // NotFound Page
    pageNotFound: '404',
    pageNotFoundMessage: 'عذراً! الصفحة غير موجودة',
    returnToHome: 'العودة إلى الصفحة الرئيسية'
  },
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    programs: 'Programs',
    activitiesNav: 'Activities',
    gallery: 'Gallery',
    contact: 'Contact',
    enrollment: 'Enrollment',
    schoolName: 'Al-Mukhtar Model Schools',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    logout: 'Logout',
    language: 'العربية',
    arabicLanguage: 'العربية',
    englishLanguage: 'English',
    mapLabel: 'Al-Mukhtar Model Schools',
    p: 'Al-Mukhtar Model Schools',
    
    // NotFound Page
    pageNotFound: '404',
    pageNotFoundMessage: 'Oops! Page not found',
    returnToHome: 'Return to Home',
    
    // About Page Education
    phD: 'Dentist',
     medCurriculum: 'Bachelor\'s in Civil Engineering',
     maPsychology: 'Gastroenterologist',
     educationBackground: 'Education Background',
     teachingExperience: 'Teaching Experience',
     certifications: 'Certifications',
     
     // Gallery Page
    galleryTitle: 'Photo Gallery',
    galleryDescription: 'Explore our vibrant school life through photos',
    gallerySubtitle: 'Explore our school facilities and student activities',
    photoCategories: 'Photo Categories',
    all: 'All',
    classrooms: 'Classrooms',
    facilities: 'Facilities',
    sportsActivity: 'Sports',
    events: 'Events',
    activities: 'Activities',
    studentsCategory: 'Students',
    noImagesFound: 'No images found',
    tryDifferentCategory: 'Try selecting a different category',
    galleryImage: 'Gallery image',
    photos: 'Photos',
    
    // Gallery Image Titles
    modernClassroom: 'Modern Classroom',
    scienceLaboratory: 'Science Laboratory',
    sportsDayActivity: 'Sports Day',
    graduation: 'Graduation 2024',
    artWorkshop: 'Art Workshop',
    schoolLibrary: 'School Library',
    groupStudy: 'Group Study',
    chemistryLab: 'Chemistry Lab',
    scienceFairActivity: 'Science Fair',
    computerLab: 'Computer Lab',
    techIntegration: 'Tech Integration',
    musicConcert: 'Music Concert',
    
    // Hero Section
    heroTitle: 'Al-Mukhtar Model Schools',
    heroSubtitle: 'Building Generations, Creating Glory',
    heroDescription: 'We provide high-quality education that combines academic excellence with Islamic values to graduate generations capable of facing future challenges',
    heroLearnMore: 'Learn More',
    enrollNow: 'Enroll Now',
    graduates: 'Graduates',
    schoolHistory: 'School History',
    leadershipTeam: 'Leadership Team',
    
    // School History
    historyParagraph1: 'Founded in 2011, Al-Mukhtar Model Schools began as a vision to provide exceptional educational opportunities for students in Damascus. Starting with just 50 students and 10 teachers, we have grown into one of Syria\'s most respected private educational institutions.',
    historyParagraph2: 'Our journey has been marked by continuous improvement and innovation in teaching methodologies, infrastructure development, and student achievement. We have consistently maintained high academic standards while adapting to modern educational needs.',
    historyParagraph3: 'Today, we proudly serve over 1700 students across all educational levels, from Kindergarten to High School, with a dedicated team of qualified educators and staff members committed to excellence in education.',
    
    // About Section
    aboutTitle: 'About Us',
    aboutDescription: 'Al-Mukhtar Model Schools is a leading educational institution established in 2011 with the aim of providing distinguished education that combines academic excellence and Islamic values',
    mission: 'Our Mission',
    missionText: 'To provide distinguished education that combines academic excellence and Islamic values, fostering a learning environment that empowers students to develop critical thinking, strong character, and the skills needed to excel in an ever-changing world and face future challenges with confidence',
    vision: 'Our Vision', 
    visionText: 'To be among the leading educational institutions in the region, recognized for our commitment to academic excellence and holistic development. We strive to create an innovative learning environment that nurtures creativity, personal growth, and academic achievement, preparing students to become successful leaders and positive contributors to society',
    values: 'Our Values',
    valuesText: 'Excellence, Innovation, Islamic Values, Respect for the Individual, Social Responsibility',
    
    // Programs
  programsTitle: 'Our Educational Programs',
  programsSubtitle: 'Comprehensive education from kindergarten to high school',
  educationalStages: 'Educational Stages',
  educationalStagesDesc: 'We offer a comprehensive educational journey designed to nurture students at every stage of their development, from early childhood through high school graduation',
  educationalStagesDescription: 'We provide integrated educational programs that meet the needs of students at all academic levels, focusing on the comprehensive development of academic and personal skills',
  coreSubjects: 'Core Subjects',
  keyFeatures: 'Key Features',
  
  // Kindergarten Features
  kindergartenFeature1: 'Safe and stimulating learning environment',
  kindergartenFeature2: 'Interactive activities developing foundational skills',
  kindergartenFeature3: 'Social and emotional skills development',
  kindergartenFeature4: 'Fostering love for learning and exploration',
  kindergartenFeature5: 'Early language skill development',
  kindergartenFeature6: 'Physical activities for motor skill development',
  kindergartenProgram: 'Kindergarten Program',
  earlyChildhood: 'Early Childhood',

   // Elementary Features
  elementaryFeature1: 'Integrated curriculum focusing on core skills',
  elementaryFeature2: 'Development of reading, writing, and math skills',
  elementaryFeature3: 'Diverse creative and artistic activities',
  elementaryFeature4: 'Building a solid foundation for later educational stages',
  elementaryFeature5: 'Building self-confidence and independence',
  elementaryFeature6: 'Developing communication and teamwork skills',
  elementaryProgram: 'Elementary School Program',
  primaryEducation: 'Primary Education',

   // Middle School Features
  middleFeature1: 'Enhancing critical thinking and problem-solving skills',
  middleFeature2: 'Developing research and analytical skills',
  middleFeature3: 'Discovering talents and personal interests',
  middleFeature4: 'Preparing students for high school',
  middleFeature5: 'Developing leadership and responsibility skills',
  middleFeature6: 'Building personal identity and self-confidence',
  middleProgram: 'Middle School Program',
  intermediateEducation: 'Intermediate Education',

   // High School Features
  highFeature1: 'Advanced academic curriculum preparing for university',
  highFeature2: 'Utlizing Ai for more efficient progressing',
  highFeature3: 'Leadership opportunities and volunteer activities',
  highFeature4: 'Comprehensive preparation for university and professional life',
  highFeature5: 'Developing critical and creative thinking skills',
  highFeature6: 'Opportunities for practical training and career experiences',
  highProgram: 'High School Program',
  secondaryEducation: 'Secondary Education',
   learnMore: 'Learn More',
  teachingApproach: 'Our Teaching Approach',
  ourTeachingApproach: 'Our Teaching Approach',
  flexibleSchedule: 'Flexible Schedule',
  flexibleScheduleDesc: 'Balanced daily schedule with academic subjects, activities, and rest periods',
  smallClassSizes: 'Small Class Sizes',
  smallClassSizesDesc: 'Maximum 20 students per class ensuring individual attention and support',
  excellenceFocus: 'Excellence Focus',
  excellenceFocusDesc: 'Commitment to academic excellence and character development',
  
  // Program Descriptions
  kindergartenDescription: 'Innovative educational program for children aged 3-5 years focusing on comprehensive development',
  elementaryDescription: 'Distinguished basic education from grades 1-6 with a focus on basic skills',
  middleDescription: 'Comprehensive middle education from grades 7-9 preparing students for high school',
  highDescription: 'Advanced secondary education preparing students for university and professional life',
  
  // Program Features
  playBasedLearning: 'Play-based learning approach',
  socialEmotionalDevelopment: 'Social and emotional development',
  socialEmotionalDev: 'Social-Emotional Development',
  basicLiteracy: 'Basic literacy and numeracy skills',
  creativeArts: 'Creative arts and crafts',
  physicalDevelopment: 'Physical development activities',
  physicalDev: 'Physical Development Activities',
  characterBuilding: 'Character building',
  comprehensiveCurriculum: 'Comprehensive curriculum',
  individualAttention: 'Individual attention',
  technologyIntegration: 'Technology integration',
  projectBasedLearning: 'Project-based learning',
  extracurricularActivities: 'Extracurricular activities',
  extracurricular: 'Extracurricular Activities',
  parentTeacherCollaboration: 'Parent-teacher collaboration',
  parentTeacherCollab: 'Parent-Teacher Collaboration',
  advancedCurriculum: 'Advanced curriculum',
  criticalThinking: 'Critical thinking development',
  leadershipOpportunities: 'Leadership opportunities',
  specializedLaboratories: 'Specialized laboratories',
  specializedLabs: 'Specialized Labs',
  careerExploration: 'Career exploration',
  peerCollaboration: 'Peer collaboration',
  universityPreparation: 'University preparation',
  universityPrep: 'University Preparation',
  advancedPlacement: 'Advanced placement courses',
  researchProjects: 'Research projects',
  collegeAdvising: 'College counseling',
  internshipOpportunities: 'Internship opportunities',
  leadershipDevelopment: 'Leadership development',
  leadershipDev: 'Leadership Development',
  
  // Subjects
  english: 'English',
  arabic: 'Arabic',
  math: 'Math',
  arts: 'Arts',
  music: 'Music',
  physicalEducation: 'Physical Education',
  mathematics: 'Mathematics',
  science: 'Science',
  socialStudies: 'Social Studies',
  advancedEnglish: 'Advanced English',
  arabicLiterature: 'Arabic Literature',
  advancedMathematics: 'Advanced Mathematics',
  physicsChemistry: 'Physics & Chemistry',
  biology: 'Biology',
  computerScience: 'Artficial Inteligent',
  physics: 'Physics',
  chemistry: 'Chemistry',
  "English": 'English',
  "Arabic": 'Arabic',
  "Math": 'Math',
  "Mathematics": 'Mathematics',
  "Science": 'Science',
  "Social Studies": 'Social Studies',
  "Physical Education": 'Physical Education',
  "Arts": 'Arts',
  "Music": 'Discovering talents',
  "Computer Science": 'Computer Science',
  "Physics": 'Physics',
  "Chemistry": 'Chemistry',
  "Biology": 'Biology',
  "Advanced English": 'Advanced English',
  "Arabic Literature": 'Arabic Literature',
  "Advanced Mathematics": 'Advanced Mathematics',
  "Physics & Chemistry": 'Physics & Chemistry',
  kindergarten: 'Kindergarten',
  kindergartenDesc: 'Innovative educational program for children aged 3-5 years focusing on comprehensive development',
  elementary: 'Elementary School',
  elementaryDesc: 'Distinguished basic education from grades 1-6 with a focus on basic skills',
  middle: 'Middle School',
  middleDesc: 'Comprehensive middle education from grades 7-9 preparing students for high school',
  high: 'High School',
  highDesc: 'Advanced secondary education preparing students for university and professional life',
    
    // Activities
    activitiesTitle: 'Activities & News',
    activitiesSubtitle: 'Discover our vibrant school community through events and achievements',
    activityCategories: 'Activity Categories',
    upcomingActivities: 'Upcoming Activities & Events',
    latestNews: 'Latest News',
    recentAchievements: 'Recent Achievements',
    scienceFair: 'Science Fair',
    scienceFairDate: 'April 13, 2025',
    scienceFairDesc: 'Rabbit dissection experiment to discover the wonders inside living organisms',
    sportsDay: 'Football league', 
    sportsDayDate: 'November 11, 2024',
    sportsDayDesc: 'A Football championship agains local schools to let our students unleash their potential',
    culturalFestival: 'Daar Al-Fikr',
    culturalFestivalDate: 'October 30, 2024',
    culturalFestDesc: 'Giving our students access to a variety of mind-blowing books',
    modelUN: 'Al-Mukhtar School Festival',
    modelUNDate: 'April 14, 2025',
    munDesc: 'Al-Mukhtar students gathering with various fun activities and events',
    musicArtsShowcase: 'Student Art Exhibition',
    musicArtsDate: 'May 24, 2025',
    artsShowcaseDesc: 'Student exhibitions of various types of drawings, both imaginative and realistic',
    mathOlympiad: 'Chess Tournament',
    mathOlympiadDate: 'December 16, 2024',
    mathOlympiadDesc: 'Chess competition between students from different schools using the European points system',
    participants150: '30 students',
    participantsAll: '11 Students',
    participants200: 'All students',
    participantsHighSchool: 'All students',
    participants80: '5 performers',
    participants30: '10 students',
    newLabTitle: 'Nurturing Computer Skills with ICDL Education',
    newLabDate: 'September 20, 2024',
    newLabSummary: 'Supporting grades 10 and 11 to prepare computer-proficient students',
    debateWinTitle: 'Our Students Participate in Regional Country Debate',
    debateWinDate: 'February 15, 2024',
    debateWinSummary: 'Debate team achieves victory in Syria local championship',
    newLibraryTitle: 'Awarding School Grants to 100+ Students',
    newLibraryDate: 'September 16, 2024',
    newLibrarySummary: 'Granting outstanding students discounts and scholarships for enrollment',
    
    // Activity Descriptions
    activityDescription1: 'Annual Robotics Competition where students compete in designing and programming robots',
    activityDescription2: 'Annual Art Exhibition showcasing students\'s artistic creations',
    activityDescription3: 'Science Museum field trip to explore applied sciences',
    activityDescription4: 'Educational summer camp combining fun and learning',
    activityDate: 'Date: May 15, 2024',
    studentAmount: 'Number of Students: 30 students',
    newsDescription1: 'School team won first place in the National Science Competition',
    newsDescription2: 'Opening of the new computer lab equipped with the latest technologies',
    newsDescription3: 'Honoring school students who excelled in the final exams',
    fieldTrip: 'Field Trip',
     roboticsCompetition: 'Robotics Competition',
     summerCamp: 'Summer Camp',
     artExhibition: 'Art Exhibition',
     bestSchoolAward: 'Best School Award 2024',
    graduationRate: 'High School Graduation Rate',
    scholarshipsAwarded: 'University Scholarships Awarded',
    sports: 'Sports',
    sportsDesc: 'Diverse sports programs to develop physical skills and team spirit',
    artsActivity: 'Arts',
    artsDesc: 'Creative art activities to develop artistic talents and creativity',
    scienceActivity: 'Science',
    scienceDesc: 'Practical scientific activities to stimulate scientific curiosity and discovery',
    community: 'Community Service',
    communityDesc: 'Community service programs to develop social responsibility',
    
    // About Page
    achievements: 'Our Achievements',
    yearsOfExcellence: 'Years of Excellence',
    students: 'Students',
    teachers: 'Teachers',
    successRate: 'Success Rate',
    
    // Contact
    contactTitle: 'Contact Us',
    contactSubtitle: "We'd love to hear from you. Please fill out the form below or reach out using our contact information.",
    contactInformation: 'Contact Information',
    contactInfo: 'Contact Information',
    addressLabel: 'Address',
    addressValue: 'Damascus, Syria',
    phone: 'Phone',
    email: 'Email',
    emailValue: 'info@al-mukhtar.edu.sy',
    workingHours: 'Working Hours',
    workingHoursValue: 'Sunday - Thursday: 8:00 AM - 3:00 PM',
    officeHours: 'Office Hours',
    administrationOffice: 'Administration Office',
    generalInformation: 'General Information',
    sendMessage: 'Send a Message',
    yourFullName: 'Your Full Name',
    yourEmail: 'Your Email',
    yourPhone: 'Your Phone Number',
    messageSubject: 'Message Subject',
    yourMessage: 'Your Message',
    sendMessageButton: 'Send Message',
    coordinates: 'Coordinates',
    followUsText: 'Follow Us',
    followUsFooter: 'Follow Us',
    contactForm: 'Contact Form',
    socialMedia: 'Social Media',
    yourName: 'Name',
    message: 'Message',
    
    // Enrollment
    enrollmentTitle: 'Enrollment',
    enrollmentProcess: 'Enrollment Process',
    step1: 'Fill the Form',
    step1Desc: 'Fill out the registration form with the required information',
    step2: 'Review',
    step2Desc: 'We will review your application and contact you',
    step3: 'Interview',
    step3Desc: 'Attend an interview with the student and parent',
    step4: 'Final Registration',
    step4Desc: 'Complete registration and pay fees',
    enrollmentHeroDesc: 'Join our educational community and start your journey towards academic excellence',
    enrollmentForm: 'Enrollment Form',
    studentInfo: 'Student Information',
    studentName: 'Student Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    selectGender: 'Select Gender',
    male: 'Male',
    female: 'Female',
    gradeLevel: 'Grade Level',
    selectGrade: 'Select Grade',
    kg1: 'KG 1',
    kg2: 'KG 2',
    grade1: 'Grade 1',
    grade2: 'Grade 2',
    grade3: 'Grade 3',
    grade4: 'Grade 4',
    grade5: 'Grade 5',
    grade6: 'Grade 6',
    grade7: 'Grade 7',
    grade8: 'Grade 8',
    grade9: 'Grade 9',
    grade10: 'Grade 10',
    grade11: 'Grade 11',
    grade12: 'Grade 12',
    previousSchool: 'Previous School',
    parentInfo: 'Parent Information',
    parentName: 'Parent Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    address: 'Address',
    additionalInfo: 'Additional Information',
    additionalNotes: 'Additional Notes',
    agreeToTerms: 'I agree to the enrollment terms and conditions and privacy policy',
    submitEnrollment: 'Submit Enrollment Application',
    requiredFields: 'Fields marked with * are required',
    tuitionFees: 'Tuition Fees',
    tuitionFeesDesc: 'Tuition fees vary by educational level. Please refer to the table below for detailed information.',
    annualFees: 'Annual Fees',
    registrationFee: 'Registration Fee',
    paymentOptions: 'Payment Options',
    paymentOptionsValue: 'Annual, Semi-annual, Quarterly',
    elementarySchool: 'Elementary School',
    middleSchool: 'Middle School',
    highSchool: 'High School',
    paymentOptionsList: 'One payment (5% discount), Two payments (beginning of each semester), Four payments (every two months)',
    paymentOptionsList1: 'One payment (5% discount)',
    paymentOptionsList2: 'Two payments (beginning of each semester)',
    paymentOptionsList3: 'Four payments (every two months)',
    feesIncludeNote: 'Fees include textbooks, school uniform, and basic activities.',
    additionalFeesNote: 'Additional fees may apply for certain activities and special trips.',
    faq: 'Frequently Asked Questions',
    faqTitle: 'Frequently Asked Questions',
    faqDocumentsQuestion: 'What documents are required for enrollment?',
    faqDocuments: 'What documents are required for enrollment?',
    faqDocumentsAnswer: 'Student birth certificate, passport copy, previous academic certificates, recent photos, medical reports (if any).',
    faqAdmissionTestQuestion: 'Is there an admission test for new students?',
    faqAdmissionTest: 'Is there an admission test for new students?',
    faqAdmissionTestAnswer: 'Yes, students undergo a placement test in English and Mathematics for grades 1 through 12.',
    faqTransportationQuestion: 'Does the school provide transportation services?',
    faqTransportation: 'Does the school provide transportation services?',
    faqTransportationAnswer: 'Yes, the school provides transportation with air-conditioned buses equipped with tracking systems and surveillance cameras to ensure student safety.',
    faqSiblingDiscountQuestion: 'Are there sibling discounts?',
    faqSiblingDiscount: 'Are there sibling discounts?',
    faqSiblingDiscountAnswer: 'Yes, the school offers a 10% discount for the second child and 15% for the third child and above.',
    successTitle: 'Application Submitted',
    successMessage: 'Your enrollment application has been submitted successfully. We will contact you soon.',
    quickLinks: 'Quick Links',
    followUs: 'Follow Us',
    schoolDescription: 'Private educational institution providing quality education from Kindergarten to High School in Damascus, Syria.',
    schoolAddress: 'Damascus, Syria',
    schoolPhone: '+963 992 514 002',
    schoolEmail: 'info@al-mukhtar.edu.sy',
    schoolNameFull: 'Al-Mukhtar Model Schools',
    administrationOfficeFooter: 'Administration Office',
    generalInformationFooter: 'General Information',
    officeHoursFooter: 'Office Hours',
    rights: '© 2025 Al-Mukhtar Model Schools. All rights reserved.',
    facebook: 'Facebook',
    facebookAr: 'فيسبوك',
    instagram: 'Instagram',
    instagramAr: 'انستغرام',
    telegram: 'Telegram',
    telegramAr: 'تلغرام',
    toggleMenu: 'Toggle menu',
    toggleMenuAr: 'فتح/إغلاق القائمة'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'ar' | 'en'>('ar');

  useEffect(() => {
    const saved = localStorage.getItem('language') as 'ar' | 'en';
    if (saved && (saved === 'ar' || saved === 'en')) {
      setLanguage(saved);
      // Ensure HTML attributes are synchronized
      document.documentElement.lang = saved;
      document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr';
    } else {
      // Set Arabic as default if no language is saved
      setLanguage('ar');
      localStorage.setItem('language', 'ar');
      document.documentElement.lang = 'ar';
      document.documentElement.dir = 'rtl';
    }
  }, []);

  const handleSetLanguage = (lang: 'ar' | 'en') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ar] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: handleSetLanguage,
      t,
      isRTL
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};